version: '3'
services:
  web:
    build: .
    image: firestore-go_web_1:local
    ports:
     - "8080:${PORT:-8080}"
    environment: 
      PORT: ${PORT:-8080}
    volumes:
      - ./wesi-formKey.json:/tmp/keys/keyfile.json:ro